// Maps the maniac's movement to sprite clips: walk cycles + single-frame idle
// stills per 8 directions (the maranza pack has no idle cycles — the frozen
// first walk frame reads as an unsettling dead stop), plus the death clip.
// Asset generated by TimeKiller/Setup/21.
using TimeKiller.Core;
using TimeKiller.Player; // FacingDirection — the shared 8-direction enum
using UnityEngine;

namespace TimeKiller.Maniac
{
    [CreateAssetMenu(menuName = "TimeKiller/Configs/Maniac Animation Set", fileName = "ManiacAnimationSet")]
    public class ManiacAnimationSet : ScriptableObject
    {
        [Tooltip("Walk cycles indexed by (int)FacingDirection.")]
        public SpriteAnimationClip[] walk = new SpriteAnimationClip[8];
        [Tooltip("Single-frame stills indexed by (int)FacingDirection.")]
        public SpriteAnimationClip[] idle = new SpriteAnimationClip[8];
        public SpriteAnimationClip death;

        [Tooltip("Playback speed never drops below this while moving.")]
        public float minAnimationSpeed = 0.4f;
        [Tooltip("Chase speed that maps to 1x walk-cycle playback (cycle fps is tuned for it).")]
        public float speedForNormalPlayback = 5.2f;

        public SpriteAnimationClip GetWalk(FacingDirection direction) => walk[(int)direction];
        public SpriteAnimationClip GetIdle(FacingDirection direction) => idle[(int)direction];
    }
}
